### ISSUE TITLE
Permission denied errors on initial run. Docker.

### ISSUE THREAD

**Issue by tehniemer** [trebonius0/Photato#31]
I'm getting a lot of permission denied errors when starting up the container. The beginning of the log is below, it's just full of the errors. There are no files being created in any of the cache directories.
```
today at 2:19 PM 2020-08-14 14:19:44 INFO photato.Photato main Starting photato
today at 2:19 PM 2020-08-14 14:19:45 INFO photato.Photato main -- Config file: /config/photato.ini
today at 2:19 PM 2020-08-14 14:19:45 INFO photato.Photato main -- Cache file: /cache
today at 2:19 PM 2020-08-14 14:19:45 INFO photato.Photato main -- Pictures file: /pictures
today at 2:19 PM 2020-08-14 14:19:47 WARNING photato.core.metadata.MetadataAggregator readFromCache Cannot read metadata from cache
today at 2:19 PM 2020-08-14 14:19:48 INFO photato.core.PhotatoFilesManager runInitialFolderExploration Exploring /pictures
today at 2:19 PM 2020-08-14 14:19:48 INFO photato.core.PhotatoFilesManager runInitialFolderExploration Exploring /pictures/Lightpainting
today at 2:19 PM 2020-08-14 14:19:48 INFO photato.core.resize.ResizedImageGenerator generateResizedPicture Generating resizedPicture for: /pictures/Lightpainting/20160216.0001.jpg lastModified: 1,569,346,845,602
today at 2:19 PM 2020-08-14 14:19:48 INFO photato.core.resize.ResizedImageGenerator generateResizedPicture Generating resizedPicture for: /pictures/Lightpainting/20160216.0005.jpg lastModified: 1,569,346,855,157
today at 2:19 PM 2020-08-14 14:19:48 INFO photato.core.resize.ResizedImageGenerator generateResizedPicture Generating resizedPicture for: /pictures/Lightpainting/20160216.0002.jpg lastModified: 1,569,346,846,052
today at 2:19 PM 2020-08-14 14:19:48 INFO photato.core.resize.ResizedImageGenerator generateResizedPicture Generating resizedPicture for: /pictures/Lightpainting/20160216.0003.jpg lastModified: 1,569,346,850,264
today at 2:19 PM java.io.FileNotFoundException: /cache/thumbnails/3faa86c8314ea31570a20a073c987850.jpg (Permission denied)
today at 2:19 PM at java.base/java.io.FileOutputStream.open0(Native Method)
today at 2:19 PM at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
today at 2:19 PM at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
today at 2:19 PM at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
today at 2:19 PM at photato.core.resize.ResizedImageGenerator.generateResizedPicture(ResizedImageGenerator.java:91)
today at 2:19 PM at photato.core.resize.thumbnails.ThumbnailGenerator.generateThumbnail(ThumbnailGenerator.java:37)
today at 2:19 PM at photato.core.PhotatoFilesManager.lambda$runInitialFolderExploration$12(PhotatoFilesManager.java:197)
today at 2:19 PM at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
today at 2:19 PM at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
today at 2:19 PM at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
today at 2:19 PM at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
today at 2:19 PM at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
today at 2:19 PM at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
today at 2:19 PM at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
today at 2:19 PM at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
today at 2:19 PM at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
today at 2:19 PM at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

Here is my compose snippet if it helps
```
## Photato - Image Gallery
  photato:
    image: trebonius0/photato:latest
    container_name: photato
    restart: unless-stopped
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "$PHOTATO_PORT:8186"
    volumes:
      - "$DOCKER_DIR/photato:/config"
      - "photato_cache:/cache"
      - "photato_thumbs:/cache/thumbnails"
      - "photato_full:/cache/fullscreen"
#      - "$PHOTO_DIR/Photato/:/cache"
#      - "$PHOTO_DIR/Photato/thumbnails:/cache/thumbnails"
#      - "$PHOTO_DIR/Photato/fullscreen:/cache/fullscreen"
      - "$PHOTO_DIR/_EXPORTS/Collections:/pictures"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=false"
      ## HTTP Routers
      - "traefik.http.routers.photato-rtr.entrypoints=https"
      - "traefik.http.routers.photato-rtr.rule=HostHeader(`photato.$DOMAINNAME`)"
      - "traefik.http.routers.photato-rtr.tls=true"
      ## Middlewares
#      - "traefik.http.routers.photato-rtr.middlewares=chain-no-auth@file" #No Authentication
#      - "traefik.http.routers.photato-rtr.middlewares=chain-basic-auth@file" #Basic Authentication
#      - "traefik.http.routers.photato-rtr.middlewares=chain-oauth@file" #Google OAuth 2.0
#      - "traefik.http.routers.photato-rtr.middlewares=chain-organizr@file" #Organizr Authentication
      - "traefik.http.routers.photato-rtr.middlewares=chain-authelia@file" #Authelia Authentication
      ## HTTP Services
      - "traefik.http.routers.photato-rtr.service=photato-svc"
      - "traefik.http.services.photato-svc.loadbalancer.server.port=8186"
```
