### ISSUE TITLE
'Photato is loading'

### ISSUE THREAD

**Issue by jtagcat** [trebonius0/Photato#33]
It's responded with a simple ` Photato is loading, please wait ... ` self-refreshing page, 12h later. It seemed to have been doing something, but logs for `Generating resizedPicture` have stopped. Is there something wrong I'm doing?

photato.ini, taken from the Windows release (for Docker‽):
```
[global]
serverPort = 8186
forceExifToolsDownload = false
forceFfmpegToolsDownload = false
addressElementsCount = 4

[index]
prefixModeOnly = true
indexFolderName = true

[thumbnail]
thumbnailQuality = 80
thumbnailHeight = 170
useParallelPicturesGeneration = true

[fullscreen]
fullScreenPictureQuality = 90
maxFullScreenPictureWitdh = 1800
maxFullScreenPictureHeight = 1200
```

compose:
```
# domain.tld is redaction
  domain.tld: # https://github.com/trebonius0/Photato
    image: trebonius0/photato
    volumes:
      - /config:/config:rw # photato.ini is in /config/
      - /cachedir:/cache:rw
      - /sourcedir:/pictures:ro
    labels:
      - traefik.frontend.rule=Host:domain.tld
      - traefik.port=8186
    networks:
      - proxy
```

logs after restarting the container:
```
2022-01-06 03:58:58 INFO photato.Photato main Starting photato
2022-01-06 03:58:58 INFO photato.Photato main -- Config file: /config/photato.ini
2022-01-06 03:58:58 INFO photato.Photato main -- Cache file: /cache
2022-01-06 03:58:58 INFO photato.Photato main -- Pictures file: /pictures
```
